profiles/urls.py
from django.urls import path
from .views import (
	signup, rating_view, revenue_view, InstallView, AdminView, add_app, role_update, CarrierSearch
)

app_name = 'profiles'

urlpatterns = [
	path('', signup, name='profile-signup'),
	path('rating/', rating_view, name='profile-rating'),
	path('revenue/', revenue_view, name='profile-revenue'),
	path('installs/', InstallView.as_view(), name='profile-install'),
	path('admin_setting/', AdminView.as_view(), name='profile-admin'),
	path('user_list/', role_update, name='profile-role'),
	path('add_app/', add_app, name='add_app'),
	path('search/<str:query>', CarrierSearch.as_view(), name='search_install'),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('social_django.urls', namespace='social'))
]

urlpatterns += [
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import App, User


class SignUpForm(UserCreationForm):
	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	email = forms.EmailField(
		label='',
		max_length=255,
		required=True,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)

	location = forms.CharField(
		label='',
		max_length=30,
		required=False,
		widget=forms.HiddenInput(
			attrs={
				"display": "none"
			}
		)
	)

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2', 'location')


class AppForm(forms.ModelForm):

	class Meta:
		model = App
		fields = '__all__'
		widgets = {
			'app_full_name': forms.Textarea(attrs={'cols': 30, 'rows': 1}),
			'app_name': forms.Textarea(attrs={'cols': 30, 'rows': 1}),
			'app_id': forms.Textarea(attrs={'cols': 30, 'rows': 1})
		}


class UserRoleForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('roles',)

	def save(self, commit=True):
		print(self.data.get('roles'))
		m = super(UserRoleForm, self).save(commit=False)
		print(m)
		print(m.__dict__)
		m.roles = self.data.get('roles')
		if commit:
			m.save()
		return m

templates/app/admin_setting.html
{% extends "base.html" %}
{% block title %}
	Admin settings
{% endblock %}

{% block content %}

    <h1>Admin settings</h1>

<div class="row">
  <div class="col-md-4">
      <div class="list-group list-group-flush mx-3 mt-4">
                  <a href="{% url 'profiles:add_app' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Add new App</span>
                  </a>
                  <a href="{% url 'profiles:profile-role'%}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-area fa-fw me-3"></i><span>Users Role Update</span>
                  </a>
                </div>
  </div></div>
{% endblock content %}

templates/app/admin_setting_appform.html
{% extends "app/admin_setting.html" %}
{% block title %}
	Admin settings
{% endblock %}

{% block content %}

    <h1>Admin settings</h1>

    <style>

        table, th, td {
          border:1px solid black;
        }

    </style>
<div class="row">
  <div class="col-md-4">
      <div class="list-group list-group-flush mx-3 mt-4">
                  <a href="{% url 'profiles:add_app' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Add new App</span>
                  </a>
                  <a href="{% url 'profiles:profile-role' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-area fa-fw me-3"></i><span>Users Role Update</span>
                  </a>
                </div>
  </div>
  <div class="col-md-8">
  {% if form %}
      <form method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
  {% endif %}

  </div>
</div>


{% endblock %}

templates/app/admin_setting_user_role.html
{% extends "base.html" %}
{% block title %}
	Admin settings
{% endblock %}

{% block content %}

    <h1>Admin settings</h1>

    <style>
        table, th, td {
          border:1px solid black;
        }

    </style>
<div class="row">
  <div class="col-md-4">
      <div class="list-group list-group-flush mx-3 mt-4">
                  <a href="{% url 'profiles:add_app' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                    <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Add new App</span>
                  </a>
                  <a href="{% url 'profiles:profile-role'%}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-area fa-fw me-3"></i><span>Users Role Update</span>
                  </a>
                </div>
  </div>
  <div class="col-md-8">
      <table>
    <caption style="caption-side:top" class="text-md-center">List of users</caption>
    <th>ID</th>
    <th>Username</th>
    <th>Name</th>
    <th>Role</th>
    {% for user in users %}
        <tr >
        <td>{{ user.id }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user }}</td>
        <td class="editable" data-id="{{ user.id }}" data-type="roles">{{ user.roles }}</td>
        </tr>

    {% endfor %}
    </table>
  </div>
</div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){
            $(document).on("dblclick",".editable",function(){
                var value=$(this).text();
                var data_type=$(this).data("type");
                var input_type="text";
                var input="<input type='"+input_type+"' class='input-data' value='"+value+"' class='form-control'>";
                $(this).html(input);
                $(this).removeClass("editable")
            });

            $(document).on("blur",".input-data",function(){
                var value=$(this).val();
                var td=$(this).parent("td");
                $(this).remove();
                td.html(value);
                td.addClass("editable");
                var type=td.data("type");
                sendToServer(td.data("id"),value,type);
            });
            $(document).on("keypress",".input-data",function(e){
                var key=e.which;
                if(key===13){
                    var value=$(this).val();
                    var td=$(this).parent("td");
                    $(this).remove();
                    td.html(value);
                    td.addClass("editable");
                   var type=td.data("type");
                   sendToServer(td.data("id"),value,type);
                }
            });

            function sendToServer(id,value,type){
                console.log(id);
                console.log(value);
                console.log(type);
                $.ajax({
                    url:"http://127.0.0.1:8000/profile/user_list/",
                    type:"POST",
                    data:{id:id,roles:value},
                })
                .done(function(response){
                    console.log(response);
                })
                .fail(function(){
                   console.log("Error Occured");
                });

            }
        });
    </script>
{% endblock %}

templates/app/dashboard.html
{% extends "base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

	<h1 class="mt-5 text-center">Welcome {{ request.user }}</h1>

    <style>
table, th, td {
  border:1px solid black;margin-left:auto;margin-right:auto;
}
caption {
  display: table-caption;
  text-align: center;
}
</style>
    <table class="mt-5 text-center">
    <caption style="caption-side:top">App List</caption>
    <th>Icon</th>
    <th>Name</th>
    <th>Package ID</th>
    {% for app in apps %}
        <tr>
        <td>{% if 'https' in app.app_img.url %}
            <img src="{{ app.app_img }}">
            {% else %}
            <img src="/media/{{ app.app_img }}">
            {% endif %}
        </td>
        <td>{{ app.app_name }}</td>
        <td>{{ app.app_id }}</td>
        </tr>

        <br>
    {% endfor %}
    </table>


{% endblock content %}

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/installs.html
{% extends "base.html" %}

{% block title %}
	Installs
    <script src="js/graph.js"></script>
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		<h1>Installs</h1>
	</div>
    <div class="row">
  <div class="col-md-4">
      <div class="list-group list-group-flush mx-3 mt-4">
          <hr/>
      <form method="POST" href="" id="dateform">
          {% csrf_token %}
          From: <input type="date" name="date__gte" value="2022-05-01" />
          <br>
          To: <input type="date" name="date__lte" value="2022-05-15" />
          <br>
          <input type="submit" value="Search">
      </form>


          <hr/>

      </div>
  </div>
  <div class="col-md-8">

    <div id="container" style="width: 75%;">
        {% if installs %}
    <table id="datatable" class="table table-bordered table-striped">
    <caption style="caption-side:top" class="text-md-center">Daily Carrier Installs Vs Date</caption>
    <thead><tr>
        <th>Date</th>
    <th>Carriers</th>
    <th>Daily Installs</th>
    </tr></thead>
    <tbody>
    {% for install in installs %}
        <tr >
        <th>{{ install.date }}</th>
        <td align="center">{{ install.carrier }}</td>
        <td align="center">{{ install.daily_installs }}</td>
        </tr>
    {% endfor %}
    </tbody>

    </table>
    <div id="chart_area" ></div>
   </div>
  {% endif %}
  </div>
</div>

{% endblock %}
{% block script %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
    <script type="text/javascript">
</script>

    <script>
        $(document).ready(function () {
            $('#selectcarrier').select2({
                dropdownAutoWidth: true,
                width: 'auto'
        })
        });
    </script>

    <script>
    Highcharts.chart('container', {
    data: {
        table: 'datatable'
    },
    chart: {
        type: 'column'
    },
    title: {
        text: 'Daily Installs VS Date'
    },
    xAxis: {
        labels: {
    step: 1
  }
    },
    yAxis: {
        allowDecimals: false,
        title: {
            text: 'Installs'
        }
    },
    tooltip: {
        formatter: function () {
            return '<b>' + this.series.name + '</b><br/>' +
                this.point.y + ' ' + this.point.name.toLowerCase();
        }
    }
});
    </script>
{% endblock %}

templates/app/ratings.html
{% extends "base.html" %}

{% block title %}
	Ratings
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		<h1>Ratings</h1>
	</div>

{% endblock %}

templates/app/revenue.html
{% extends "base.html" %}

{% block title %}
	Revenue
{% endblock %}

{% block content %}
	
    <div class="text-left mt-5 container">
		<h1>Revenue</h1>
	</div>

{% endblock %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	<div class="col-md-4">
		
		<div class="list-group mt-5">
		    <a href="{% url 'users:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
			{% if profile %}
		    <a href="{% url 'profiles:profile-signup' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Profile Sign up
		    	{% else %}
		    	<a href="{% url 'users:sign-up' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Sign up
		    {% endif %}		    	
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Profile</a>
		</div>

	</div>

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		    <p>or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2" href="{% url "social:begin" "google-oauth2" %}">
		        <i class="fa fa-google-plus"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}